name: TestLibrary


env:
  SOLUTION_FILE_PATH: RedFoxMath_Test.sln
  BUILD_CONFIGURATION: Release

on:
  push:
    branches: [ "master" ]

jobs: 
  test: 
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set PowerShell Execution Policy
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        Write-Host "ExecutionPolicy is now:" (Get-ExecutionPolicy)

    - name: Install NuGet
      run: |
        Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe

    - name: NuGet restore
      run: ./nuget.exe restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run tests
      run: ./x64/Release/RedFoxEngine_UnitTest.exe